### ISSUE TITLE
대출 서비스 엔티티와 CRUD api

### ISSUE THREAD

**Issue by ahngj96** [f-lab-edu/Libaray#12]
* 대출 서비스 엔티티 작성
* 대출 서비스 CRUD api 구현

**Comment by icraft2170** [comment]
@ahngj96 
Rental 관련 엔티티 필드 변경 및 로직을 작성해 보았는데, 
한 번 얘기해보면 좋을 것 같아 태그를 남겨 두었습니다.
한 번 확인해 보시고 피드백 부탁드려요 😀😀😀

**Comment by ahngj96** [comment]
렌탈 엔티티 독립적인 식별자 필요합니다 ㅎㅎ
